# alembic.ini (template)
# Copie/edite este arquivo se precisar personalizar o Alembic.
# O env.py já está configurado para sobrescrever sqlalchemy.url a partir de app.config.settings.DATABASE_URL
[alembic]
script_location = alembic
# sqlalchemy.url será sobrescrito pelo alembic/env.py (lendo de suas configurações)
sqlalchemy.url = driver://user:pass@localhost/dbname

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
